services:
  mosquitto:
    build:
      context: ../dams-mosquitto
      dockerfile: Dockerfile
    container_name: benchmark-mosquitto-pm2
    ports:
      - "1883:1883"
      - "9100:9100"
    networks:
      - benchmark-net
    volumes:
      - ./broker-configs/mosquitto-pm2.conf:/etc/mosquitto/mosquitto.conf
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  # Benchmark Test Runner
  benchmark-runner:
    build:
      context: .
      dockerfile: Dockerfile.benchmark
    container_name: benchmark-runner-pm2
    depends_on:
      - mosquitto
    networks:
      - benchmark-net
    volumes:
      - ./results:/app/results
      - ./test-configs:/app/test-configs
    environment:
      - BROKER_ADDRESS=mosquitto
      - BROKER_PORT=1883
      - NODE_EXPORTER_URL=http://mosquitto:9100/metrics
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    command: /bin/bash -c "tail -f /dev/null"

networks:
  benchmark-net:
    driver: bridge
