services:
  mosquitto:
    build:
      context: .
      dockerfile: Dockerfile.legacy_broker_w_node_exporter
    container_name: benchmark-mosquitto-baseline
    ports:
      - "1883:1883"
      - "9100:9100"
    networks:
      - benchmark-net
    volumes:
      - ./broker-configs/mosquitto-baseline.conf:/mosquitto/config/mosquitto.conf

  # Benchmark Test Runner
  benchmark-runner:
    build:
      context: .
      dockerfile: Dockerfile.benchmark
    container_name: benchmark-runner-baseline
    depends_on:
      - mosquitto
    networks:
      - benchmark-net
    volumes:
      - ./results:/app/results
      - ./logs:/app/logs
    environment:
      - BROKER_ADDRESS=mosquitto
      - BROKER_PORT=1883
      - NODE_EXPORTER_URL=http://mosquitto:9100/metrics
    command: /bin/bash -c "tail -f /dev/null"

networks:
  benchmark-net:
    driver: bridge
